### PR TITLE
Python 3.X compatible

### PR DESCRIPTION
**Pull request by teaearlgraycold**
At least for me, I couldn't get this working in 3.4.3 without these changes

### CODE REVIEW

**Comment by barneygale** [comment]
I was pretty ashamed of my python code, so I've rewritten most of this little utility now. I made most of the same adjustments as you, though I handle `input()/raw_input()` a little differently as iirc `input()` isn't safe in python2.

Could you check that it works OK for you now?

**Comment by teaearlgraycold** [comment]
Great! Workin' fine from what I can tell.

Although, unless it's standard practice, I think changing it from:

    rcon = mcrcon.MCRcon(host, port, pass)

to

    rcon = mcrcon.MCRcon()
    rcon.connect(host, port)
    rcon.login(pass)

Makes it a little bit too bulky.

**Comment by barneygale** [comment]
I think it's nicer because the project is intended as explanatory and educational. It's also useful to be able to catch exceptions at more points, and in demo.py it's clearer if something has gone wrong during connection or login.

**Comment by teaearlgraycold** [comment]
Fair enough

**Pull request closed without merging**
